

POST   http://localhost:4000/Product
Content-Type: application/json


{
    "name":"hp mouse",
    "descrption":"wireless mouse",
    "price":"550"
}

###
GET http://localhost:4000/Product/allProducts


###
GET  http://localhost:4000/Product/3503b01e-7f48-4bbd-8962-dc15ba7660a8